name = "no-smoke-walk-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "no-smoke-walk-api-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "no-smoke-walk-api"
vars = { ENVIRONMENT = "production" }