name = "no-smoke-walk-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development", ABUSE_GUARD = "false" }

[env.production]  
vars = { ENVIRONMENT = "production", ABUSE_GUARD = "true" }