name = "no-smoke-walk-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[env.development]
vars = { ENVIRONMENT = "development", ABUSE_GUARD = "false" }

[env.production]
vars = { ENVIRONMENT = "production", ABUSE_GUARD = "true" }

# KV namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

# CORS configuration
[build]
command = "npm run build"

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]